// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw_oG1UJ1hj8ySoVg5PLTjHoeqgghbff4',
    appId: '1:416336168755:web:a08a4a307444156dc9a046',
    messagingSenderId: '416336168755',
    projectId: 'gratistellar',
    authDomain: 'gratistellar.firebaseapp.com',
    storageBucket: 'gratistellar.firebasestorage.app',
    measurementId: 'G-D7T32WBHM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw_oG1UJ1hj8ySoVg5PLTjHoeqgghbff4',
    appId: '1:416336168755:android:c3d0f3e6d5e8f0a7c9a046',
    messagingSenderId: '416336168755',
    projectId: 'gratistellar',
    storageBucket: 'gratistellar.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw_oG1UJ1hj8ySoVg5PLTjHoeqgghbff4',
    appId: '1:416336168755:web:a08a4a307444156dc9a046',
    messagingSenderId: '416336168755',
    projectId: 'gratistellar',
    authDomain: 'gratistellar.firebaseapp.com',
    storageBucket: 'gratistellar.firebasestorage.app',
    measurementId: 'G-D7T32WBHM8',
  );
}