// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeVsWLnvPSDDYIyxWfeWCkAa9sAY3NxK4',
    appId: '1:416336168755:web:aabee0e72317df93c9a046',
    messagingSenderId: '416336168755',
    projectId: 'gratistellar',
    authDomain: 'gratistellar.firebaseapp.com',
    storageBucket: 'gratistellar.firebasestorage.app',
    measurementId: 'G-RWD64NXK44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZXGZ8FHDf3tjF_jq9FQJCdp9fD18VXg0',
    appId: '1:416336168755:android:12621fccc7dfe466c9a046',
    messagingSenderId: '416336168755',
    projectId: 'gratistellar',
    storageBucket: 'gratistellar.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeVsWLnvPSDDYIyxWfeWCkAa9sAY3NxK4',
    appId: '1:416336168755:web:eacbefde7904f850c9a046',
    messagingSenderId: '416336168755',
    projectId: 'gratistellar',
    authDomain: 'gratistellar.firebaseapp.com',
    storageBucket: 'gratistellar.firebasestorage.app',
    measurementId: 'G-NB0TJLKZPQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOIqR1Zc3MPFUT356HtJ0GdSrtZJ_WtBY',
    appId: '1:416336168755:ios:8a538c0dd090e511c9a046',
    messagingSenderId: '416336168755',
    projectId: 'gratistellar',
    storageBucket: 'gratistellar.firebasestorage.app',
    androidClientId: '416336168755-ohke806pcd2g25vba7sec5hqtlotqeqm.apps.googleusercontent.com',
    iosClientId: '416336168755-85f22vhdtrgmh54vbt8kn29upcqume2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.gratistellar',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOIqR1Zc3MPFUT356HtJ0GdSrtZJ_WtBY',
    appId: '1:416336168755:ios:8a538c0dd090e511c9a046',
    messagingSenderId: '416336168755',
    projectId: 'gratistellar',
    storageBucket: 'gratistellar.firebasestorage.app',
    androidClientId: '416336168755-ohke806pcd2g25vba7sec5hqtlotqeqm.apps.googleusercontent.com',
    iosClientId: '416336168755-85f22vhdtrgmh54vbt8kn29upcqume2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.gratistellar',
  );

}